[package]
name = "phaktionz"
version = "1.2.3"
authors = ["mustafif0929@gmail.com <mustafif0929@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
