#!/bin/bash
# To make the debian package
echo "Version: "
read version
cargo build
cp target/debug/phaktionz phaktionz/usr/bin/
dpkg-deb --build phaktionz

mv phaktionz.deb ~/MKProjects/debian/phaktionz-$version.deb
