#!/bin/bash
# To make the debian package
echo "Version: "
read version
cargo build
cp target/debug/phaktionz phaktionz/usr/bin/
dpkg-deb --build phaktionz

mkdir ~/MKProjects/MKProj/debian/Phaktionz/$version
mv phaktionz.deb ~/MKProjects/MKProj/debian/Phaktionz/$version
