name: phaktionz # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.2.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Phaktionz CLI Wiki # 79 char long summary
description: |
  The Phaktionz CLI Wiki is to bring the ability of getting information 
  about Phaktionz directly on your system.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
apps: 
  phaktionz:
    command: bin/phaktionz
parts:
  phaktionz:
    # See 'snapcraft plugins'
    plugin: dump
    plugin: rust
    source-type: git
    source: "https://github.com/MKProj/Phaktionz-CLI.git"