---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          cargo build --verbose && cargo test --verbose

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "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"
          prerelease: false
          files: |
            target/release/phaktionz